#!/usr/bin/env perl

use 5.012;
use strict; use warnings;
use POSIX qw/ strftime mktime /;
use Time::Local qw/ timegm_nocheck /;
use Getopt::Std;

my %opt;
getopts('y:', \%opt);

my $year = $opt{y} || (localtime)[5];
for my $j (1..366) {
    say strftime("%m/%d/%Y (%j)", gmtime(timegm_nocheck(0, 0, 0, $j, 0, $year)));
}
